create datadir if not exist
I was getting 2019-10-28T22:34:33.591Z SetupListener: Currently using local geth
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/jsidhu/Library/Application Support/Syscoin/testnet3/geth/syscoin-relayer.log'
Emitted 'error' event at:

because my data dir didn't exist, so we should create it to avoid this from happening